[project]
name = "qa-chatbot"
version = "0.1.0"
description = "GenAI based QA chatbot"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chromadb>=1.1.0",
    "google-genai>=1.38.0",
    "pandas>=2.3.2",
    "streamlit>=1.49.1",
]
